import { Event } from './models/event.model';

export const EVENT_DATA: Event[] = [
  {
    id: 1,
    name: 'Exposição Agropecuária 1',
    startDate: new Date(),
    endDate: new Date(),
    place: 'Parque de exposições',
    city: 'Maringá',
    state: 'PR',
    progressStatus: 'Em andamento',
    status: 'Ativo',
    urlImage: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
  },
  {
    id: 2,
    name: 'Exposição Agropecuária 2',
    startDate: new Date(),
    endDate: new Date(),
    place: 'Parque de exposições',
    city: 'Maringá',
    state: 'PR',
    progressStatus: 'Em andamento',
    status: 'Ativo',
    urlImage: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
  },
  {
    id: 3,
    name: 'Exposição Agropecuária 3',
    startDate: new Date(),
    endDate: new Date(),
    place: 'Parque de exposições',
    city: 'Maringá',
    state: 'PR',
    progressStatus: 'Em andamento',
    status: 'Ativo',
    urlImage: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
  },
  {
    id: 4,
    name: 'Exposição Agropecuária 4',
    startDate: new Date(),
    endDate: new Date(),
    place: 'Parque de exposições',
    city: 'Maringá',
    state: 'PR',
    progressStatus: 'Em andamento',
    status: 'Ativo',
    urlImage: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
  },
  {
    id: 5,
    name: 'Exposição Agropecuária 5',
    startDate: new Date(),
    endDate: new Date(),
    place: 'Parque de exposições',
    city: 'Maringá',
    state: 'PR',
    progressStatus: 'Em andamento',
    status: 'Ativo',
    urlImage: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
  },
  {
    id: 6,
    name: 'Exposição Agropecuária 6',
    startDate: new Date(),
    endDate: new Date(),
    place: 'Parque de exposições',
    city: 'Maringá',
    state: 'PR',
    progressStatus: 'Em andamento',
    status: 'Ativo',
    urlImage: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
  },
  {
    id: 7,
    name: 'Exposição Agropecuária 7',
    startDate: new Date(),
    endDate: new Date(),
    place: 'Parque de exposições',
    city: 'Maringá',
    state: 'PR',
    progressStatus: 'Em andamento',
    status: 'Ativo',
    urlImage: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
  },
  {
    id: 8,
    name: 'Exposição Agropecuária 8',
    startDate: new Date(),
    endDate: new Date(),
    place: 'Parque de exposições',
    city: 'Maringá',
    state: 'PR',
    progressStatus: 'Em andamento',
    status: 'Ativo',
    urlImage: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
  },
  {
    id: 9,
    name: 'Exposição Agropecuária 9',
    startDate: new Date(),
    endDate: new Date(),
    place: 'Parque de exposições',
    city: 'Maringá',
    state: 'PR',
    progressStatus: 'Em andamento',
    status: 'Ativo',
    urlImage: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
  },
  {
    id: 10,
    name: 'Exposição Agropecuária 10',
    startDate: new Date(),
    endDate: new Date(),
    place: 'Parque de exposições',
    city: 'Maringá',
    state: 'PR',
    progressStatus: 'Em andamento',
    status: 'Ativo',
    urlImage: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
  },
];
